Repository sprint4-16/global-nomad, pull requests merged in 2024-05, with the labels that each got.

#13 feat: 리액트 설정 완료
  package-lock.json
  package.json
  src/pages/_app.tsx
Labels: 기능 추가

#18 hotfix: 웹폰트 mixin 추가 및 오타 수정
  src/styles/_colors.scss
  src/styles/_font.scss
  src/styles/globals.scss
Labels: hotfix

#23 hotfix: storybook svgr 에러 처리
  .storybook/main.ts
  globals.d.ts
  next.config.mjs
  tsconfig.json
Labels: hotfix

#19 Button 컴포넌트 구현
  package-lock.json
  src/components/Button/Button.module.scss
  src/components/Button/Button.stories.ts
  src/components/Button/Button.tsx
  src/stories/Button.tsx
  src/styles/_colors.scss
  src/styles/globals.scss
Labels: 기능 추가

#20 Side Navigation Menu UI 구현
  public/icon/icon_empty.svg
  public/icon/icon_pen.svg
  public/img/img_resource_profile_img_sample.png
  public/img/img_resource_profile_img_sample.svg
  src/components/SideNavigationMenu/SideNavigationMenu.module.scss
  src/components/SideNavigationMenu/SideNavigationMenu.scss
  src/components/SideNavigationMenu/SideNavigationMenu.tsx
  src/components/SideNavigationMenu/SideNavigationType.ts
  src/styles/_colors.scss
Labels: 기능 추가

#25 Card Resource 구현
  public/icon/icon_star_bold.svg
  public/img/img_resource_street_dance.png
  src/components/CardResource/CardContent.module.scss
  src/components/CardResource/CardContent.tsx
  src/components/CardResource/CardResource.module.scss
  src/components/CardResource/CardResource.tsx
  src/components/CardResource/CardResourceType.ts
Labels: 기능 추가

#24 feat: gnb, footer 제작 및 배치
  public/img/profile.svg
  src/components/Footer/Footer.module.scss
  src/components/Footer/Footer.stories.tsx
  src/components/Footer/Footer.tsx
  src/components/GlobalNavigationBar/GlobalNavigationBar.module.scss
  src/components/GlobalNavigationBar/GlobalNavigationBar.stories.tsx
  src/components/GlobalNavigationBar/GlobalNavigationBar.tsx
  src/components/GlobalNavigationBar/NavItems/NavItems.module.scss
  src/components/GlobalNavigationBar/NavItems/Navitems.tsx
  src/components/GlobalNavigationBar/NavItems/items/ButtonAlertIcon.module.scss
  src/components/GlobalNavigationBar/NavItems/items/ButtonAlertIcon.tsx
  src/components/GlobalNavigationBar/NavItems/items/ButtonProfile.module.scss
  src/components/GlobalNavigationBar/NavItems/items/ButtonProfile.tsx
  src/components/GlobalNavigationBar/NavItems/items/index.ts
  src/components/index.tsx
  src/constants/index.tsx
  src/pages/_app.tsx
  src/styles/_colors.scss
  src/styles/_font.scss
  src/styles/_z-index.scss
  src/styles/globals.scss
Labels: 기능 추가

#26 feat: Category&Filter, Pagination 컴포넌트 UI 및 기본 기능 제작
  public/btn/btn_arrow_down.svg
  src/components/Category&Filter/Category/Category.module.scss
  src/components/Category&Filter/Category/Category.tsx
  src/components/Category&Filter/Filter/Filter.module.scss
  src/components/Category&Filter/Filter/Filter.tsx
  src/components/Category&Filter/Filter/FilterList.tsx
  src/components/Pagination/PageBtn.tsx
  src/components/Pagination/Pagination.module.scss
  src/components/Pagination/Pagination.tsx
  src/pages/index.tsx
Labels: 기능 추가

#34 hotfix: 별 style 수정
  src/components/CardResource/CardContent.module.scss
  src/components/CardResource/CardResource.tsx
Labels: hotfix

#38 fix: 폰트 중복작성 제거
  src/components/Button/Button.module.scss
Labels: fix

#28 feat: input 컴포넌트 UI
  public/btn/btn_chevron_down.svg
  public/btn/btn_chevron_up.svg
  public/icon/icon_checkmark.svg
  src/components/DateInput/DateInput.module.scss
  src/components/DateInput/DateInput.tsx
  src/components/Dropdown/Dropdown.module.scss
  src/components/Dropdown/Dropdown.tsx
  src/components/Input/Input.module.scss
  src/components/Input/Input.tsx
  src/custom.d.ts
  src/styles/_colors.scss
Labels: 기능 추가

#40 feat: popup 컴포넌트 구현 및 배치
  public/icon/icon_check.svg
  src/components/Footer/Footer.module.scss
  src/components/Popup/PopupComponent.tsx
  src/components/Popup/PopupComponents/AlertModal.module.scss
  src/components/Popup/PopupComponents/AlertModal.stories.tsx
  src/components/Popup/PopupComponents/AlertModal.tsx
  src/components/Popup/PopupComponents/Confirmation.module.scss
  src/components/Popup/PopupComponents/Confirmation.stories.tsx
  src/components/Popup/PopupComponents/ConfirmationModal.tsx
  src/hooks/useOutsideClick.ts
  src/pages/_app.tsx
  src/styles/_colors.scss
  src/styles/_font.scss
  src/styles/_z-index.scss
Labels: 기능 추가

#51 fix: storybook 문제 해결 및 이름 수정
  src/components/Button/Button.stories.ts
  src/components/Footer/Footer.stories.tsx
  src/components/GlobalNavigationBar/GlobalNavigationBar.stories.tsx
  src/components/Popup/PopupComponents/AlertModal.stories.tsx
  src/components/Popup/PopupComponents/Confirmation.stories.tsx
  src/components/btns/AddImageBtn/AddImageBtn.stories.ts
  src/components/btns/ArrowBtn/ArrowBtn.stories.ts
  src/components/btns/CloseBtn/CloseBtn.stories.ts
  src/components/btns/ControlTimeBtn/ControlTimeBtn.stories.ts
  src/components/btns/DeleteBtn/DeleteBtn.stories.ts
  src/components/btns/KebabBtn/KebabBtn.stories.ts
  src/components/btns/NotificationBtn/Notification.stories.ts
  src/components/btns/VisibilityBtn/VisibilityBtn.stories.ts
Labels: fix

#45 feat 후기 작성 컴포넌트 디자인 및 기본 기능 구현
  src/components/Popup/CreatePopupModal.tsx
  src/components/Popup/CreateReviewModal.tsx
  src/components/Popup/PopupComponents/AlertModal/AlertModal.module.scss
  src/components/Popup/PopupComponents/AlertModal/AlertModal.stories.tsx
  src/components/Popup/PopupComponents/AlertModal/AlertModal.tsx
  src/components/Popup/PopupComponents/ConfirmationModal/ConfirmationModal.module.scss
  src/components/Popup/PopupComponents/ConfirmationModal/ConfirmationModal.stories.tsx
  src/components/Popup/PopupComponents/ConfirmationModal/ConfirmationModal.tsx
  src/components/Popup/PopupComponents/ReviewModal/RaitingComponent/RaitingComponent.module.scss
  src/components/Popup/PopupComponents/ReviewModal/RaitingComponent/RaitingComponent.tsx
  src/components/Popup/PopupComponents/ReviewModal/ReviewModal.module.scss
  src/components/Popup/PopupComponents/ReviewModal/ReviewModal.stories.tsx
  src/components/Popup/PopupComponents/ReviewModal/ReviewModal.tsx
  src/components/Textarea/Textarea.module.scss
  src/components/Textarea/Textarea.stories.tsx
  src/components/Textarea/Textarea.tsx
  src/hooks/useOutsideClick.ts
  src/styles/_font.scss
Labels: 기능 추가

#47 feat: Search 컴포넌트 제작
  public/icon/icon_bed.svg
  src/components/Search/Search.module.scss
  src/components/Search/Search.tsx
  src/custom.d.ts
Labels: 기능 추가

#57 refactor: filter 컴포넌트 재사용성을 위한 기존의 filterList Props로 변경
  src/components/Category&Filter/Filter/Filter.tsx
  src/components/Category&Filter/Filter/FilterList.tsx
Labels: refactor

#59 feat: 예약 현황 페이지 디자인 구현 및 컴포넌트 수정
  package-lock.json
  public/btn/btn_next_arrow.svg
  public/btn/btn_prev_arrow.svg
  public/icon/icon_ellipse_blue.svg
  public/icon/icon_ellipse_gray.svg
  src/components/Chips/Chips.module.scss
  src/components/Chips/Chips.tsx
  src/components/Dropdown/Dropdown.module.scss
  src/components/Dropdown/Dropdown.tsx
  src/components/SideNavigationMenu/SideNavigationMenu.module.scss
  src/components/SideNavigationMenu/SideNavigationMenu.tsx
  src/constants/index.tsx
  src/pageLayouts/ReservationCalendarLayout/ReservationCalendarLayout.module.scss
  src/pageLayouts/ReservationCalendarLayout/ReservationCalendarLayout.tsx
  src/pageLayouts/ReservationCalendarLayout/components/CalendarLayout/CalendarLayout.module.scss
  src/pageLayouts/ReservationCalendarLayout/components/CalendarLayout/CalendarLayout.tsx
  src/pageLayouts/ReservationCalendarLayout/components/CreateCalendar/CreateCalendar.module.scss
  src/pageLayouts/ReservationCalendarLayout/components/CreateCalendar/CreateCalendar.tsx
  src/pageLayouts/commonLayouts/SideNavigationMenuLayout/SideNavigationMenuLayout.module.scss
  src/pageLayouts/commonLayouts/SideNavigationMenuLayout/SideNavigationMenuLayout.tsx
  src/pages/_app.tsx
  src/pages/user/reservation-calendar/index.tsx
  src/styles/_colors.scss
  src/styles/_font.scss
Labels: 기능 개선, 기능 추가

#52 feat: floating box 컴포넌트 UI 구현
  public/icon/icon_add.svg
  public/icon/icon_stroke.svg
  public/icon/icon_subtract.svg
  src/components/Category&Filter/Category/Category.tsx
  src/components/Category&Filter/Filter/Filter.tsx
  src/components/Category&Filter/Filter/FilterList.tsx
  src/components/FloatingBox/DateInfo.tsx
  src/components/FloatingBox/FloatingBox.module.scss
  src/components/FloatingBox/FloatingBox.tsx
  src/components/FloatingBox/HeadCountInfo.tsx
  src/components/FloatingBox/PriceInfo.tsx
  src/components/FloatingBox/priceDataForm.ts
  src/components/Pagination/PageBtn.tsx
  src/components/Pagination/Pagination.tsx
Labels: 기능 추가

#54 Card 컴포넌트 구현
  public/icon/index.tsx
  src/components/Card/Card.module.scss
  src/components/Card/Card.tsx
  src/components/Card/Components/CardDropdown.module.scss
  src/components/Card/Components/CardDropdown.tsx
  src/components/Card/Components/ReservationButton.module.scss
  src/components/Card/Components/ReservationButton.tsx
  src/components/Card/ReservationDetailCard.module.scss
  src/components/Card/ReservationDetailCard.tsx
  src/constants/index.tsx
  src/hooks/useClickOutside.tsx
  src/styles/_colors.scss
  src/styles/_font.scss
Labels: 기능 추가

#68 66 refactor card 컴포넌트 수정
  public/btn/btn_meatball.svg
  src/components/Card/Card.module.scss
  src/components/Card/Card.tsx
  src/components/Card/Components/CardDropdown.module.scss
  src/components/Card/Components/CardDropdown.tsx
  src/components/Card/Components/ReservationButton.module.scss
  src/components/Card/Components/ReservationButton.tsx
  src/components/Card/components/CardComponents.tsx
  src/pages/card/ExperienceCard.tsx
  src/pages/card/ReservationCard.tsx
  src/pages/card/ReservationDetailCard.module.scss
  src/pages/card/ReservationDetailCard.tsx
  src/pages/card/ReviewCard.tsx
Labels: refactor

#64 refactor: 기능 추가 및 개선
  next.config.mjs
  package-lock.json
  package.json
  src/apis/apiHooks/Auth.ts
  src/apis/apiHooks/MyReservations.ts
  src/apis/axiosInstance.ts
  src/components/Button/Button.module.scss
  src/components/Button/Button.tsx
  src/components/Footer/Footer.tsx
  src/components/GlobalNavigationBar/GlobalNavigationBar.tsx
  src/components/GlobalNavigationBar/NavItems/Navitems.tsx
  src/components/GlobalNavigationBar/NavItems/items/ButtonAlertIcon.tsx
  src/components/GlobalNavigationBar/NavItems/items/ButtonProfile.module.scss
  src/components/GlobalNavigationBar/NavItems/items/ButtonProfile.tsx
  src/components/GlobalNavigationBar/NavItems/items/index.ts
  src/components/Popup/PopupComponents/AlertModal/AlertModal.module.scss
  src/components/Popup/PopupComponents/AlertModal/AlertModal.tsx
  src/components/Popup/PopupComponents/ConfirmationModal/ConfirmationModal.module.scss
  src/components/Popup/PopupComponents/ConfirmationModal/ConfirmationModal.tsx
  src/components/Popup/PopupComponents/ReviewModal/RaitingComponent/RaitingComponent.tsx
  src/components/Popup/PopupComponents/ReviewModal/ReviewModal.module.scss
  src/components/Popup/PopupComponents/ReviewModal/ReviewModal.tsx
  src/components/Textarea/Textarea.tsx
  src/constants/index.tsx
  src/hooks/useCookies.ts
  src/pages/card/ReviewCard.tsx
Labels: 기능 개선, 기능 추가, refactor
