Repository sprint4-16/global-nomad, pull requests merged in 2024-06, with the labels that each got.

#70 feat: 이미지 최적화
  next.config.mjs
  package-lock.json
  package.json
  src/components/Card/Card.tsx
  src/components/Card/components/CardComponents.tsx
  src/hooks/useClickOutside.tsx
  src/pages/card/ReviewCard.tsx
Labels: 기능 개선, 기능 추가

#71 feat: 카카오 지도 api를 활용한 Map 공통 컴포넌트 기능 구현
  package-lock.json
  package.json
  public/icon/icon_location.svg
  public/icon/icon_location_white.svg
  src/components/Map/Map.module.scss
  src/components/Map/Map.tsx
  src/components/Map/components/KakaoMap.module.scss
  src/components/Map/components/KakaoMap.tsx
  src/components/Map/hooks/ResettingMapBounds.ts
  src/hooks/useKakaoAPI.tsx
  src/styles/_z-index.scss
Labels: 기능 추가

#76 feat: 내 정보 페이지 구현
  package-lock.json
  package.json
  public/img/img_resource_default_profile.png
  public/img/img_resource_profile_img_sample.png
  src/apis/apiHooks/MyProfile.ts
  src/components/Button/Button.module.scss
  src/components/Button/Button.tsx
  src/components/Input/Input.module.scss
  src/components/Input/Input.tsx
  src/components/MyPage/MyPageForm/MyPageForm.module.scss
  src/components/MyPage/MyPageForm/MyPageForm.tsx
  src/components/SideNavigationMenu/SideNavigationMenu.module.scss
  src/components/SideNavigationMenu/SideNavigationMenu.tsx
  src/components/btns/VisibilityBtn/VisibilityBtn.tsx
  src/constants/index.tsx
  src/pageLayouts/MyPageLayout/MyPageLayout.module.scss
  src/pageLayouts/MyPageLayout/MyPageLayout.tsx
  src/pages/_app.tsx
  src/pages/my-page/index.tsx
  src/pages/user/index.tsx
  src/styles/_font.scss
Labels: 기능 추가

#77 feat: 내 체험관리 페이지 구현
  src/apis/apiHooks/MyReservations.ts
  src/constants/index.tsx
  src/pageLayouts/ActivityLayout/ActivityLayout.module.scss
  src/pageLayouts/ActivityLayout/ActivityLayout.tsx
  src/pageLayouts/ReservationCalendarLayout/ReservationCalendarLayout.module.scss
  src/pages/user/activities/index.tsx
  src/styles/_font.scss
Labels: 기능 추가

#72 [feat] 예약 내역 페이지 구현
  package-lock.json
  package.json
  src/apis/apiHooks/Auth.ts
  src/apis/apiHooks/MyReservations.ts
  src/components/Card/Card.module.scss
  src/components/Card/components/CardComponents.tsx
  src/components/Category&Filter/Filter/Filter.module.scss
  src/components/Category&Filter/Filter/Filter.tsx
  src/components/Category&Filter/Filter/FilterList.tsx
  src/components/GlobalNavigationBar/NavItems/items/ButtonProfile.tsx
  src/components/Popup/CreateReviewModal.tsx
  src/constants/index.tsx
  src/hooks/useCookies.ts
  src/pages/_app.tsx
  src/pages/card/ReservationCard.tsx
  src/pages/user/reservations/index.tsx
  src/pages/user/reservations/reservations.module.scss
  src/styles/_z-index.scss
Labels: 기능 추가

#84 [feat] 예약 현황 페이지 api 데이터 불러오기
  package-lock.json
  src/apis/apiHooks/MyActivities.ts
  src/components/Category&Filter/Category/Category.module.scss
  src/components/Category&Filter/Category/Category.tsx
  src/components/Dropdown/Dropdown.module.scss
  src/components/Dropdown/Dropdown.tsx
  src/pageLayouts/ReservationCalendarLayout/ReservationCalendarLayout.tsx
  src/pageLayouts/ReservationCalendarLayout/components/CalendarLayout/CalendarLayout.module.scss
  src/pageLayouts/ReservationCalendarLayout/components/CalendarLayout/CalendarLayout.tsx
  src/pageLayouts/ReservationCalendarLayout/components/CreateCalendar/CreateCalendar.tsx
  src/pages/user/reservation-calendar/index.tsx
Labels: 기능 추가

#79 41 feat popover 컴포넌트 UI
  package-lock.json
  package.json
  src/components/Dropdown/Dropdown.module.scss
  src/components/Popover/NotificationPopover/Notification.tsx
  src/components/Popover/NotificationPopover/NotificationPopover.module.scss
  src/components/Popover/NotificationPopover/NotificationPopover.tsx
  src/components/Popover/Popover.module.scss
  src/components/Popover/ReservationDatePickPopover/ReservationDatePickPopover.module.scss
  src/components/Popover/ReservationDatePickPopover/ReservationDatePickPopover.stories.ts
  src/components/Popover/ReservationDatePickPopover/ReservationDatePickPopover.tsx
  src/components/Popover/ReservationInfoPopover/ReservationInfoPopover.module.scss
  src/components/Popover/ReservationInfoPopover/ReservationInfoPopover.tsx
  src/components/Popover/components/Header/Header.module.scss
  src/components/Popover/components/Header/Header.tsx
  src/components/Popover/index.tsx
  src/pages/card/ReservationDetailCard.module.scss
  src/pages/card/ReservationDetailCard.tsx
  src/pages/index.tsx
  src/stories/Button.stories.ts
  src/stories/Button.tsx
  src/stories/Configure.mdx
  src/stories/Header.stories.ts
  src/stories/Header.tsx
  src/stories/Page.stories.ts
  src/stories/Page.tsx
  src/stories/assets/accessibility.png
  src/stories/assets/accessibility.svg
  src/stories/assets/addon-library.png
  src/stories/assets/assets.png
  src/stories/assets/avif-test-image.avif
  src/stories/assets/context.png
  src/stories/assets/discord.svg
  src/stories/assets/docs.png
  src/stories/assets/figma-plugin.png
  src/stories/assets/github.svg
  src/stories/assets/share.png
  src/stories/assets/styling.png
  src/stories/assets/testing.png
  src/stories/assets/theming.png
  src/stories/assets/tutorials.svg
  src/stories/assets/youtube.svg
  src/stories/button.css
  src/stories/header.css
  src/stories/page.css
Labels: 기능 추가

#65 feat: floating box 캘린더 UI 연동
  src/components/FloatingBox/DateInfo.tsx
  src/components/FloatingBox/FloatingBox.module.scss
  src/components/FloatingBox/FloatingBox.tsx
Labels: 기능 추가

#85 feat: 예약 내역 페이지 무한 스크롤 기능 구현
  src/apis/apiHooks/MyReservations.ts
  src/components/Category&Filter/Filter/Filter.tsx
  src/components/Popup/PopupComponents/AlertModal/AlertModal.module.scss
  src/components/Popup/PopupComponents/AlertModal/AlertModal.tsx
  src/components/Popup/PopupComponents/ConfirmationModal/ConfirmationModal.module.scss
  src/components/Popup/PopupComponents/ConfirmationModal/ConfirmationModal.tsx
  src/components/Popup/PopupComponents/ReviewModal/ReviewModal.module.scss
  src/components/Popup/PopupComponents/ReviewModal/ReviewModal.tsx
  src/hooks/useBlockScroll.ts
  src/pageLayouts/ReservationsLayout/ReservationsLayout.tsx
  src/pageLayouts/ReservationsLayout/reservationsLayout.module.scss
  src/pages/card/ReservationCard.tsx
  src/pages/user/reservations/index.tsx
Labels: 기능 추가

#93 feat: 예약현황 페이지 기능 구현 및 리팩토링
  src/apis/apiHooks/MyActivities.ts
  src/components/Chips/Chips.tsx
  src/components/Dropdown/Dropdown.module.scss
  src/components/Dropdown/Dropdown.tsx
  src/components/Popover/Popover.module.scss
  src/components/Popover/ReservationInfoPopover/CreateModal.tsx
  src/components/Popover/ReservationInfoPopover/ReservationInfoPopover.module.scss
  src/components/Popover/ReservationInfoPopover/ReservationInfoPopover.tsx
  src/components/Popover/ReservationInfoPopover/components/NavList/NavList.module.scss
  src/components/Popover/ReservationInfoPopover/components/NavList/NavList.tsx
  src/components/Popover/ReservationInfoPopover/components/ReservationCardSection/CreateCardList/CreateCardList.module.scss
  src/components/Popover/ReservationInfoPopover/components/ReservationCardSection/CreateCardList/CreateCardList.tsx
  src/components/Popover/ReservationInfoPopover/components/ReservationCardSection/CreateCardList/ReservationDetailCard/ReservationDetailCard.module.scss
  src/components/Popover/ReservationInfoPopover/components/ReservationCardSection/CreateCardList/ReservationDetailCard/ReservationDetailCard.tsx
  src/components/Popover/ReservationInfoPopover/components/ReservationCardSection/Footer/Footer.module.scss
  src/components/Popover/ReservationInfoPopover/components/ReservationCardSection/Footer/Footer.tsx
  src/components/Popover/ReservationInfoPopover/components/ReservationCardSection/ReservationCardSection.module.scss
  src/components/Popover/ReservationInfoPopover/components/ReservationCardSection/ReservationCardSection.tsx
  src/components/Popover/ReservationInfoPopover/components/ScheduleDropdown/ScheduleDropdown.module.scss
  src/components/Popover/ReservationInfoPopover/components/ScheduleDropdown/ScheduleDropdown.tsx
  src/components/Popover/components/Header/Header.module.scss
  src/components/Popover/index.tsx
  src/components/SideNavigationMenu/SideNavigationMenu.tsx
  src/pageLayouts/ReservationCalendarLayout/components/CalendarLayout/CalendarLayout.tsx
  src/pageLayouts/ReservationCalendarLayout/components/CreateCalendar/CreateCalendar.tsx
  src/pages/_app.tsx
  src/styles/_colors.scss
Labels: 기능 개선, 기능 추가, refactor

#94 feat: 메인 페이지 체험 불러오기 기능 및 페이지네이션
  src/apis/apiHooks/Activities.ts
  src/components/CardResource/CardContent.module.scss
  src/components/Category&Filter/Category/Category.module.scss
  src/components/Category&Filter/Category/Category.tsx
  src/components/Category&Filter/Filter/Filter.module.scss
  src/components/Category&Filter/Filter/FilterList.tsx
  src/components/Pagination/Pagination.module.scss
  src/components/Pagination/Pagination.tsx
  src/pageLayouts/MainPageLayout/ActivityListLayout/ActivityListLayout.module.scss
  src/pageLayouts/MainPageLayout/ActivityListLayout/ActivityListLayout.tsx
  src/pageLayouts/ReservationCalendarLayout/components/CalendarLayout/CalendarLayout.tsx
  src/pages/index.tsx
  src/styles/_mixins.scss
Labels: 기능 추가

#97 feat: 메인 페이지 배너 및 인기 체험
  package-lock.json
  public/btn/index.tsx
  public/img/img_resource_error.png
  src/apis/apiHooks/MyReservations.ts
  src/components/CardResource/CardContent.module.scss
  src/components/CardResource/CardContent.tsx
  src/components/CardResource/CardResource.module.scss
  src/components/CardResource/CardResource.tsx
  src/components/CardResource/CardResourceType.ts
  src/components/Search/Search.module.scss
  src/components/Search/Search.tsx
  src/hooks/useResizeHook.tsx
  src/pageLayouts/LandingLayout/landingLayout.module.scss
  src/pageLayouts/LandingLayout/landingLayout.tsx
  src/pageLayouts/LandingLayout/popularExperiences.module.scss
  src/pageLayouts/LandingLayout/popularExperiences.tsx
  src/pages/index.tsx
  src/styles/_z-index.scss
  src/styles/globals.scss
Labels: 기능 추가

#104 feat: 예약 현황 페이지의 모든 추가 기능 구현
  src/components/Chips/Chips.tsx
  src/components/Popover/ReservationInfoPopover/CreateModal.tsx
  src/components/Popover/ReservationInfoPopover/CreateReservationModal.module.scss
  src/components/Popover/ReservationInfoPopover/CreateReservationModal.tsx
  src/components/Popover/ReservationInfoPopover/ReservationInfoPopover.module.scss
  src/components/Popover/ReservationInfoPopover/ReservationInfoPopover.tsx
  src/components/Popover/ReservationInfoPopover/components/ReservationCardSection/CreateCardList/CreateCardList.tsx
  src/components/Popover/ReservationInfoPopover/components/ReservationCardSection/CreateCardList/ReservationDetailCard/ReservationDetailCard.tsx
  src/components/Popover/ReservationInfoPopover/components/ReservationCardSection/Footer/Footer.module.scss
  src/components/Popover/ReservationInfoPopover/components/ReservationCardSection/Footer/Footer.tsx
  src/components/Popover/ReservationInfoPopover/components/ReservationCardSection/ReservationCardSection.module.scss
  src/components/Popover/ReservationInfoPopover/components/ReservationCardSection/ReservationCardSection.tsx
  src/components/Popup/PopupComponents/AlertModal/AlertModal.tsx
  src/hooks/useBlockScroll.ts
  src/hooks/useOutsideClick.ts
  src/pageLayouts/ReservationCalendarLayout/components/CalendarLayout/CalendarLayout.module.scss
  src/pageLayouts/ReservationCalendarLayout/components/CalendarLayout/CalendarLayout.tsx
  src/pageLayouts/ReservationCalendarLayout/components/CreateCalendar/CreateCalendar.module.scss
  src/pageLayouts/ReservationCalendarLayout/components/CreateCalendar/CreateCalendar.tsx
Labels: 기능 개선, 기능 추가, refactor

#92 90 feat 체험 상세 페이지 구현
  .eslintrc.json
  public/btn/btn_meatball.svg
  public/icon/icon_star_on.svg
  src/apis/apiHooks/Review.ts
  src/apis/apiHooks/temporary.ts
  src/components/CustomedDatePicker/CustomedDatePicker.tsx
  src/components/FloatingBox/DateInfo.tsx
  src/components/FloatingBox/FloatingBox.module.scss
  src/components/FloatingBox/FloatingBox.tsx
  src/components/Map/Map.module.scss
  src/components/Map/Map.tsx
  src/components/btns/KebabBtn/KebabBtn.tsx
  src/constants/index.tsx
  src/pages/_app.tsx
  src/pages/activities/Activity.module.scss
  src/pages/activities/[activityId].tsx
  src/pages/activities/_skeleton-ui/skeleton-header/index.tsx
  src/pages/activities/_skeleton-ui/skeleton-header/skeleton-header.module.scss
  src/styles/datepicker_custom.scss
  src/styles/globals.scss
  src/types/activities.types.ts
  src/types/review.types.ts
Labels: 기능 추가

#108 refactor: 컴포넌트 단일 책임 원칙에 따른 리팩토링
  src/components/Chips/Chips.tsx
  src/components/Popover/ReservationInfoPopover/CreateReservationModal.module.scss
  src/components/Popover/ReservationInfoPopover/CreateReservationModal.tsx
  src/components/Popover/ReservationInfoPopover/ReservationInfoPopover.module.scss
  src/components/Popover/ReservationInfoPopover/ReservationInfoPopover.tsx
  src/components/Popover/ReservationInfoPopover/components/CreateCardList/CreateCardList.module.scss
  src/components/Popover/ReservationInfoPopover/components/CreateCardList/CreateCardList.tsx
  src/components/Popover/ReservationInfoPopover/components/CreateCardList/Footer/Footer.module.scss
  src/components/Popover/ReservationInfoPopover/components/CreateCardList/Footer/Footer.tsx
  src/components/Popover/ReservationInfoPopover/components/CreateCardList/ReservationDetailCard/ReservationDetailCard.module.scss
  src/components/Popover/ReservationInfoPopover/components/CreateCardList/ReservationDetailCard/ReservationDetailCard.tsx
  src/components/Popover/ReservationInfoPopover/components/ReservationCardSection/CreateCardList/CreateCardList.tsx
  src/components/Popover/ReservationInfoPopover/components/ReservationCardSection/ReservationCardSection.module.scss
  src/components/Popover/ReservationInfoPopover/components/ReservationCardSection/ReservationCardSection.tsx
  src/components/Popover/ReservationInfoPopover/components/ScheduleDropdown/ScheduleDropdown.module.scss
  src/components/Popup/AlertModal/AlertModal.module.scss
  src/components/Popup/AlertModal/AlertModal.stories.tsx
  src/components/Popup/AlertModal/AlertModal.tsx
  src/components/Popup/ConfirmationModal/ConfirmationModal.module.scss
  src/components/Popup/ConfirmationModal/ConfirmationModal.stories.tsx
  src/components/Popup/ConfirmationModal/ConfirmationModal.tsx
  src/components/Popup/CreatePopupModal.tsx
  src/components/Popup/CreateReviewModal.tsx
  src/components/Popup/ReviewModal/RaitingComponent/RaitingComponent.module.scss
  src/components/Popup/ReviewModal/RaitingComponent/RaitingComponent.tsx
  src/components/Popup/ReviewModal/ReviewModal.module.scss
  src/components/Popup/ReviewModal/ReviewModal.stories.tsx
  src/components/Popup/ReviewModal/ReviewModal.tsx
  src/pageLayouts/ReservationCalendarLayout/ReservationCalendarLayout.tsx
  src/pageLayouts/ReservationCalendarLayout/components/CalendarLayout/CalendarLayout.tsx
  src/pageLayouts/ReservationCalendarLayout/components/CreateCalendar/CreateCalendar.tsx
Labels: 기능 개선, refactor, fix

#98 feat: 내 체험 등록 페이지 기능 구현
  package-lock.json
  package.json
  src/apis/apiHooks/PostActivities.ts
  src/components/ActivityPost/ActivityPostForm/ActivityPostForm.tsx
  src/components/AddressInput/AddressInput.module.scss
  src/components/AddressInput/AddressInput.tsx
  src/components/Input/Input.tsx
  src/components/btns/AddImageBtn/AddImageBtn.tsx
Labels: 기능 추가

#105 feat 메인페이지 구현
  src/components/CardResource/CardContent.module.scss
  src/components/CardResource/CardContent.tsx
  src/components/CardResource/CardResource.module.scss
  src/components/CardResource/CardResourceSmall.module.scss
  src/components/CardResource/CardResourceSmall.tsx
  src/components/Search/Search.tsx
  src/pageLayouts/LandingLayout/ActivityListLayout.module.scss
  src/pageLayouts/LandingLayout/ActivityListLayout.tsx
  src/pageLayouts/LandingLayout/SearchedListLayout.tsx
  src/pageLayouts/LandingLayout/landingLayout.tsx
  src/pageLayouts/LandingLayout/popularExperiences.tsx
  src/pageLayouts/MainPageLayout/ActivityListLayout/ActivityListLayout.tsx
  src/pages/index.tsx
  src/styles/_font.scss
  src/styles/globals.scss
Labels: 기능 추가

#113 fix, refactor: 에러 및 코드 컨벤션 변경 및 기능 개선
  src/apis/apiHooks/Activities.ts
  src/apis/apiHooks/Auth.ts
  src/components/ActivityPost/ActivityPostForm/ActivityPostForm.tsx
  src/components/Button/Button.tsx
  src/components/Card/components/CardComponents.tsx
  src/components/Category&Filter/Category/Category.tsx
  src/components/Dropdown/Dropdown.tsx
  src/components/GlobalNavigationBar/NavItems/Navitems.tsx
  src/components/GlobalNavigationBar/NavItems/items/ButtonProfile.tsx
  src/components/Map/Map.tsx
  src/components/Search/Search.tsx
  src/constants/index.tsx
  src/pageLayouts/ActivityLayout/ActivityLayout.tsx
  src/pageLayouts/LandingLayout/Components/ActivityListLayout/ActivityListLayout.module.scss
  src/pageLayouts/LandingLayout/Components/ActivityListLayout/index.tsx
  src/pageLayouts/LandingLayout/Components/Carousel/index.tsx
  src/pageLayouts/LandingLayout/Components/PopularExperiences/PopularExperiences.module.scss
  src/pageLayouts/LandingLayout/Components/PopularExperiences/index.tsx
  src/pageLayouts/LandingLayout/Components/SearchedListLayout/index.tsx
  src/pageLayouts/LandingLayout/Components/index.ts
  src/pageLayouts/LandingLayout/LandingLayout.module.scss
  src/pageLayouts/LandingLayout/index.tsx
  src/pageLayouts/LandingLayout/landingLayout.tsx
  src/pageLayouts/ReservationCalendarLayout/ReservationCalendarLayout.tsx
  src/pages/auth/_layout/authLayout.module.scss
  src/pages/auth/_layout/index.tsx
  src/pages/auth/signin/index.tsx
  src/pages/card/ExperienceCard.tsx
  src/pages/index.tsx
  src/pages/my-page/index.tsx
  src/pages/user/index.tsx
Labels: 기능 개선, refactor, fix

#117 fix: 간단한 에러 수정
  src/apis/apiHooks/Auth.ts
  src/pageLayouts/LandingLayout/Components/ActivityListLayout/index.tsx
  src/pageLayouts/LandingLayout/Components/PopularExperiences/index.tsx
  src/pageLayouts/ReservationCalendarLayout/ReservationCalendarLayout.tsx
  src/pages/auth/signup/index.tsx
Labels: fix

#119 fix: 내 체험 수정, 등록 페이지 오류 수정
  src/apis/apiHooks/PostActivities.ts
  src/components/ActivityEdit/ActivityEditForm/ActivityEditForm.tsx
  src/components/ActivityPost/ActivityPostForm/ActivityPostForm.tsx
  src/components/DateInput/DateInput.tsx
  src/components/Dropdown/Dropdown.tsx
  src/components/MyPage/MyPageForm/MyPageForm.module.scss
  src/components/MyPage/MyPageForm/MyPageForm.tsx
  src/constants/index.tsx
  src/pageLayouts/LandingLayout/Components/Carousel/index.tsx
  src/pageLayouts/LandingLayout/SlickLayout.module.scss
  src/pageLayouts/MyPageLayout/MyPageLayout.module.scss
Labels: 기능 개선

#118 100 feat 메인페이지 결합
  package-lock.json
  package.json
  src/apis/apiHooks/Auth.ts
  src/apis/apiHooks/MyActivities.ts
  src/apis/apiHooks/temporary.ts
  src/components/FloatingBox/FloatingBox.tsx
  src/components/GlobalNavigationBar/NavItems/NavItems.module.scss
  src/components/GlobalNavigationBar/NavItems/Navitems.tsx
  src/components/GlobalNavigationBar/NavItems/items/ButtonAlertIcon.module.scss
  src/components/GlobalNavigationBar/NavItems/items/ButtonAlertIcon.tsx
  src/components/GlobalNavigationBar/NavItems/items/ButtonProfile.tsx
  src/components/Popover/NotificationPopover/Notification.tsx
  src/components/Popover/NotificationPopover/NotificationPopover.module.scss
  src/components/Popover/NotificationPopover/NotificationPopover.tsx
  src/components/Popover/ReservationInfoPopover/ReservationInfoPopover.tsx
  src/components/Popover/ReservationInfoPopover/components/CreateCardList/ReservationDetailCard/ReservationDetailCard.tsx
  src/components/Popover/components/Header/Header.tsx
  src/constants/index.tsx
  src/firebase/changeStatusInFireBase.tsx
  src/firebase/index.tsx
  src/firebase/saveActivityToFirebase.tsx
  src/pages/activities/[activityId].tsx
Labels: 기능 추가

#123 fix: 타입 에러 수정
  src/components/ActivityEdit/ActivityEditForm/ActivityEditForm.tsx
  src/components/ActivityPost/ActivityPostForm/ActivityPostForm.tsx
  src/components/Input/Input.tsx
  src/components/MyPage/MyPageForm/MyPageForm.tsx
Labels: fix

#127 fix: 내 정보 페이지 변경 시 gnb에 바로 반영되게 수정
  src/components/GlobalNavigationBar/NavItems/Navitems.tsx
  src/components/MyPage/MyPageForm/MyPageForm.tsx
Labels: fix

#130 fix: error boundary 적용
  src/components/ErrorBoundary/ErrorBoundary.module.scss
  src/components/ErrorBoundary/ErrorBoundary.tsx
  src/pages/_app.tsx
Labels: fix

#132 fix: 자잘한 오류 수정
  src/apis/apiHooks/MyProfile.ts
  src/apis/apiHooks/MyReservations.ts
  src/apis/apiHooks/Review.ts
  src/apis/apiHooks/temporary.ts
  src/components/ActivityEdit/ActivityEditForm/ActivityEditForm.tsx
  src/components/ActivityPost/ActivityPostForm/ActivityPostForm.tsx
Labels: fix

#136 fix: 에러 수정 및 리팩토링
  src/apis/apiHooks/Review.ts
  src/components/ErrorBoundary/ErrorBoundary.tsx
  src/components/GlobalNavigationBar/NavItems/Navitems.tsx
  src/components/Popover/ReservationInfoPopover/components/CreateCardList/ReservationDetailCard/ReservationDetailCard.tsx
  src/components/Popup/ReviewModal/RaitingComponent/RaitingComponent.tsx
  src/constants/index.tsx
  src/pageLayouts/ActivityDetailLayout/ActivityDetailLayout.module.scss
  src/pageLayouts/ActivityDetailLayout/components/ArticleSection/ArticleSection.module.scss
  src/pageLayouts/ActivityDetailLayout/components/ArticleSection/index.tsx
  src/pageLayouts/ActivityDetailLayout/components/DescriptionSection/DexcriptionSection.module.scss
  src/pageLayouts/ActivityDetailLayout/components/DescriptionSection/index.tsx
  src/pageLayouts/ActivityDetailLayout/components/ReviewSection/ReviewSection.module.scss
  src/pageLayouts/ActivityDetailLayout/components/ReviewSection/index.tsx
  src/pageLayouts/ActivityDetailLayout/index.tsx
  src/pages/_app.tsx
  src/pages/activities/[activityId].tsx
  src/pages/activities/_skeleton-ui/skeleton-header/index.tsx
  src/types/activities.types.ts
Labels: 기능 개선, 기능 추가, refactor, fix
